### ISSUE TITLE
CI/CD with GitHub actions

### ISSUE THREAD

**Issue by kraikov** [paulrberg/solidity-template#30]
I'm trying to create a CI/CD action that runs test whenever new PR is created targeting the main branch.

Here is the yaml configuration:

```
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MNEMONIC: ${{secrets.MNEMONIC}}
      INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
      QUORUM_URL: ${{secrets.QUORUM_URL}}
      QUORUM_PK: ${{secrets.QUORUM_PK}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run test
 ```

However whenever the tests are ran, the typechain folder can't be resolved:

```
> hardhat test

Downloading compiler 0.7.4
Compiling 16 files with 0.7.4
Compilation finished successfully
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
An unexpected error occurred:

Error: test/utils.ts(3,23): error TS2307: Cannot find module '../typechain' or its corresponding type declarations.
```

Any ideas? I don't want to push the typechain folder and I assume it should be generated the same way it's generated locally?

- Operating system and its version: Mac OS 11.2
- yarn version: 1.22.10
- node.js version: v14.15.4
- hardhat version: 2.0.6

**Comment by kraikov** [comment]
Fixed it by adding a compilation step before running the tests:

```
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MNEMONIC: ${{secrets.MNEMONIC}}
      INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
      QUORUM_URL: ${{secrets.QUORUM_URL}}
      QUORUM_PK: ${{secrets.QUORUM_PK}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    **- run: npm compile**
    - run: npm run test
```
